/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vbzmelpvugyixagfiftu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiem1lbHB2dWd5aXhhZ2ZpZnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNzc1MDQsImV4cCI6MjA3Nzk1MzUwNH0.5sQPUvuXtGm-WuPSr6ke-22T4X7pd5vMUi8Y6ZWhUs4"